[package]
name = "rust-2d-game-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.23"
eframe = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "5.0"

[lib]
name = "rust_2d_game_engine"
path = "src/lib.rs"