[package]
name = "rust-2d-game-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.20"
egui-winit = "0.20"
egui-wgpu = "0.20"
wgpu = "0.16"
pollster = "0.3"
winit = "0.27" 

[lib]
name = "rust_2d_game_engine"
path = "src/lib.rs"